# Generated by Django 3.2.5 on 2021-11-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('developer', models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack')], max_length=200, null=True)),
                ('languages1', models.CharField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript')], max_length=200, null=True)),
                ('languages2', models.CharField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript')], max_length=200, null=True)),
                ('languages3', models.CharField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript')], max_length=200, null=True)),
                ('project', models.ImageField(upload_to='')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkin_link', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('address', models.TextField()),
            ],
        ),
    ]
