# Generated by Django 3.2.5 on 2021-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0002_auto_20211111_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
