# Generated by Django 3.2.5 on 2021-11-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0003_auto_20211111_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='facebook_link',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='linkin_link',
            new_name='linkin',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='address',
        ),
    ]
