# Generated by Django 3.2.5 on 2021-11-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0004_auto_20211111_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='github_link',
            new_name='github',
        ),
    ]
