# Generated by Django 3.2.5 on 2021-11-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0005_rename_github_link_portfolio_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='github',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='linkin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
