# Generated by Django 3.2.5 on 2021-11-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0006_auto_20211111_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='description',
            new_name='what_you_do',
        ),
    ]
